#include "libavcodec/codec.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <X11/Xlib.h>
#include <X11/X.h>
#include <X11/Xutil.h>
#include <libavcodec/avcodec.h>
#include <libavutil/opt.h>
#include <libavutil/imgutils.h>


const char(*ffmpegError[]) = {
  [EPERM] = 	" Operation not permitted ",
  [ENOENT] = 	" No such file or directory ",
  [ESRCH] = 	" No such process ",
  [EINTR] = 	" Interrupted system call",
  [EIO] = 	" Input/output error ",
  [ENXIO] = 	" Device not configured ",
  [E2BIG] = 	" Argument list too long ",
  [ENOEXEC] = 	" Exec format error ",
  [EBADF] = 	" Bad file descriptor ",
  [ECHILD] = 	" No child processes ",
  [EDEADLK] =   " Resource deadlock avoided ",
  [ENOMEM] = 	" Cannot allocate memory ",
  [EACCES] = 	" Permission denied ",
  [EFAULT] = 	" Bad address ",
  [ENOTBLK] =   " Block device required ",
  [EBUSY] = 	" Device busy ",
  [EEXIST] = 	" File exists ",
  [EXDEV] = 	" Cross-device link ",
  [ENODEV] = 	" Operation not supported by device ",
  [ENOTDIR] =	" Not a directory ",
  [EISDIR] = 	" Is a directory ",
  [EINVAL] = 	" Invalid argument ",
  [ENFILE] = 	" Too many open files in system ",
  [EMFILE] = 	" Too many open files ",
  [ENOTTY] = 	" Inappropriate ioctl for device",
  [ETXTBSY] =	" Text file busy ",
  [EFBIG] = 	" File too large ",
  [ENOSPC] = 	" No space left on device ",
  [ESPIPE] = 	" Illegal seek ",
  [EROFS] = 	" Read-only filesystem",
  [EMLINK] = 	" Too many links ",
  [EPIPE] = 	" Broken pipe ",
  [EDOM] = 	" Numerical argument out of domain ",
  [ERANGE] = 	" Result too large ",
  [EAGAIN] = 	" Resource temporarily unavailable ",
  [EINPROGRESS] = 	" Operation now in progress ",
  [EALREADY] = 	" Operation already in progress ",
  [ENOTSOCK] = 	" Socket operation on non-socket ",
  [EDESTADDRREQ] = 	" Destination address required ",
  [EMSGSIZE] = 	" Message too long ",
  [EPROTOTYPE] = 	" Protocol wrong type for socket ",
  [ENOPROTOOPT] = 	" Protocol not available ",
  [EPROTONOSUPPORT] =	" Protocol not supported ",
  [ESOCKTNOSUPPORT] =	" Socket type not supported ",
  [EOPNOTSUPP] = 	" Operation not supported ",
  [EPFNOSUPPORT] = 	" Protocol family not supported ",
  [EAFNOSUPPORT] = 	" Address family not supported by protocol family ",
  [EADDRINUSE] = 	" Address already in use ",
  [EADDRNOTAVAIL] = 	" Can't assign requested address ",
  [ENETDOWN] = 	" Network is down ",
  [ENETUNREACH] = 	" Network is unreachable ",
  [ENETRESET] = 	" Network dropped connection on reset ",
  [ECONNABORTED] = 	" Software caused connection abort ",
  [ECONNRESET] = 	" Connection reset by peer ",
  [ENOBUFS] =	" No buffer space available ",
  [EISCONN] =	" Socket is already connected ",
  [ENOTCONN] = 	" Socket is not connected ",
  [ESHUTDOWN] = 	" Can't send after socket shutdown ",
  [ETOOMANYREFS] = 	" Too many references: can't splice ",
  [ETIMEDOUT] = 	" Operation timed out ",
  [ECONNREFUSED] = 	" Connection refused ",
  [ELOOP] = 	" Too many levels of symbolic links ",
  [ENAMETOOLONG] = 	" File name too long ",
  [EHOSTDOWN] = 	" Host is down ",
  [EHOSTUNREACH] = 	" No route to host ",
  [ENOTEMPTY] = 	" Directory not empty ",
};
